use std::fmt::Write as _;
use std::path::Path;

fn main() {
    embuild::espidf::sysenv::output();

    // ── config.toml → generated constants ──────────────────────────────────
    println!("cargo:rerun-if-changed=config.toml");

    let config_src = std::fs::read_to_string("config.toml").expect("failed to read config.toml");
    let config: toml::Value = config_src.parse().expect("invalid config.toml");

    let mut gen = String::from(
        "// Auto-generated by build.rs from config.toml — do not edit.\n\n",
    );

    // [pins]
    let pins = config.get("pins").expect("missing [pins] in config.toml");
    for (key, gpio) in [
        ("factory_reset", "PIN_FACTORY_RESET"),
        ("motor_in1", "PIN_MOTOR_IN1"),
        ("motor_in2", "PIN_MOTOR_IN2"),
        ("motor_nslp", "PIN_MOTOR_NSLP"),
        ("enc_a", "PIN_ENC_A"),
        ("enc_b", "PIN_ENC_B"),
        ("led", "PIN_LED"),
    ] {
        let v = pins.get(key).unwrap_or_else(|| panic!("missing pins.{key}"));
        writeln!(gen, "pub const {gpio}: i32 = {v};").unwrap();
    }

    // [motor]
    let motor = config
        .get("motor")
        .expect("missing [motor] in config.toml");

    let freq = motor
        .get("pwm_freq_hz")
        .expect("missing motor.pwm_freq_hz");
    writeln!(gen, "\npub const PWM_FREQ_HZ: u32 = {freq};").unwrap();

    let mode_str = motor
        .get("mode")
        .expect("missing motor.mode")
        .as_str()
        .expect("motor.mode must be a string");
    let mode_variant = match mode_str {
        "PhEn" => "PhEn",
        "InIn" => "InIn",
        other => panic!("unknown motor.mode \"{other}\" — expected \"PhEn\" or \"InIn\""),
    };
    writeln!(
        gen,
        "pub const MOTOR_MODE: crate::motor::MotorMode = crate::motor::MotorMode::{mode_variant};"
    )
    .unwrap();

    let min_duty = motor.get("min_duty").expect("missing motor.min_duty");
    writeln!(gen, "pub const MIN_DUTY: i32 = {min_duty};").unwrap();

    // [door]
    let door = config.get("door").expect("missing [door] in config.toml");
    for (key, name, ty) in [
        ("dead_zone", "DEAD_ZONE", "i32"),
        ("endstop_open", "ENDSTOP_OPEN", "i32"),
        ("endstop_closed", "ENDSTOP_CLOSED", "i32"),
        ("endstop_ramp_counts", "ENDSTOP_RAMP_COUNTS", "i32"),
        ("remote_power", "REMOTE_POWER", "i32"),
        ("idle_timeout_ms", "IDLE_TIMEOUT_MS", "u64"),
        ("loop_period_ms", "LOOP_PERIOD_MS", "u64"),
    ] {
        let v = door.get(key).unwrap_or_else(|| panic!("missing door.{key}"));
        writeln!(gen, "pub const {name}: {ty} = {v};").unwrap();
    }
    for (key, name) in [
        ("assist_gain", "ASSIST_GAIN"),
        ("lpf_alpha", "LPF_ALPHA"),
    ] {
        let v = door.get(key).unwrap_or_else(|| panic!("missing door.{key}"));
        // Ensure the literal has a decimal point for f32
        let s = v.to_string();
        let literal = if s.contains('.') {
            s
        } else {
            format!("{s}.0")
        };
        writeln!(gen, "pub const {name}: f32 = {literal};").unwrap();
    }

    let invert = door
        .get("invert_direction")
        .expect("missing door.invert_direction");
    writeln!(gen, "pub const INVERT_DIRECTION: bool = {invert};").unwrap();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("config_generated.rs");
    std::fs::write(&dest, gen).expect("failed to write config_generated.rs");

    // ── secrets.toml → DEF_* env vars ──────────────────────────────────────
    println!("cargo:rerun-if-changed=secrets.toml");

    let path = Path::new("secrets.toml");
    if !path.exists() {
        return;
    }

    let contents = std::fs::read_to_string(path).expect("failed to read secrets.toml");
    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, val)) = line.split_once('=') {
            let key = key.trim();
            let val = val.trim().trim_matches('"');
            println!("cargo:rustc-env=DEF_{}={}", key.to_uppercase(), val);
        }
    }
}
